/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd.DietitionRole;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Enterprise.FoodWellnessEnterprise;
import Backend.Network.Network;
import Backend.Organization.OrganizationDietition;
import Backend.Organization.Organization;
import Backend.User.User;
import Backend.WorkQueue.DietitionWorkRequest;
import FrontEnd.FitUSACustomer.CustomerLoginWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anky
 */
public class DietitionRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DietitionRequestJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private User userAccount;
    private EcoSystem system;
    private Network sourceNetwork;
    private Network targetNetwork;
    
    public DietitionRequestJPanel(JPanel userProcessContainer, User account, Enterprise enterprise, EcoSystem system, Network sourceNetwork, Network targetNetwork) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
            this.enterprise = enterprise;
            this.userAccount = account;
            this.system = system;
            this.sourceNetwork = sourceNetwork;
            this.targetNetwork = targetNetwork;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLABLE1 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        RequestTaskButton = new javax.swing.JButton();
        back = new javax.swing.JButton();
        imagelabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLABLE1.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        JLABLE1.setForeground(new java.awt.Color(102, 0, 0));
        JLABLE1.setText("Enterprise :");
        jPanel1.add(JLABLE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));
        jPanel1.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 90, 30));

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel1.setText("Message  ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));
        jPanel1.add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 180, -1));

        RequestTaskButton.setBackground(new java.awt.Color(204, 204, 255));
        RequestTaskButton.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        RequestTaskButton.setForeground(new java.awt.Color(0, 102, 102));
        RequestTaskButton.setText("Request Appointment");
        RequestTaskButton.setBorderPainted(false);
        RequestTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestTaskButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RequestTaskButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 330, 30));

        back.setBackground(new java.awt.Color(204, 204, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setText("Back");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 570, 320));

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wallpaperflare.com_wallpaper (10) (1).jpg"))); // NOI18N
        add(imagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerLoginWorkAreaJPanel clwjp = (CustomerLoginWorkAreaJPanel) component;
        clwjp.populateRequestTable(sourceNetwork);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backActionPerformed

    private void RequestTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestTaskButtonActionPerformed
        // TODO add your handling code here:
        String message = messageJTextField.getText();
        if (!message.isEmpty()) {
            DietitionWorkRequest request = new DietitionWorkRequest();
            request.setMessage(message);
            request.setSender(userAccount);
            request.setStatus("Sent");

            Organization org = null;
            Enterprise ent = null;
            if (sourceNetwork != targetNetwork) {
                for (Enterprise enterprise : targetNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof FoodWellnessEnterprise) {
                        ent = enterprise;
                    }
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof OrganizationDietition) {
                            org = organization;
                            break;
                        }
                    }
                }
            } else {
                for (Enterprise enterprise : sourceNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof FoodWellnessEnterprise) {
                        ent = enterprise;
                    }
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof OrganizationDietition) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct input");
        }
        messageJTextField.setText("");
    }//GEN-LAST:event_RequestTaskButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLABLE1;
    private javax.swing.JButton RequestTaskButton;
    private javax.swing.JButton back;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
