/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd.BeauticianRole;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Network.Network;
import Backend.Organization.OrganizationNutritionConsulatant;
import Backend.Organization.Organization;
import Backend.Organization.OrganizationBeautySalon;
import Backend.User.User;
import Backend.WorkQueue.NutritionistWorkRequest;
import Backend.WorkQueue.BeauticianWorkRequest;
import Backend.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anky
 */
public class WorkAreaSalonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkAreaSalonJPanel
     */
    private JPanel userProcessContainer;
    private OrganizationBeautySalon salonorganization;
    private Enterprise enterprise;
    private User userAccount;
    private EcoSystem system;
    private Network sourceNetwork;
    private Network targetNetwork;  
    
    public WorkAreaSalonJPanel(JPanel userProcessContainer, User account, Organization organization, Enterprise enterprise, EcoSystem system, Network sourceNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.salonorganization = (OrganizationBeautySalon) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        this.sourceNetwork = sourceNetwork;
        valueLabel.setText(organization.getName());
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        organizationjLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignjButton = new javax.swing.JButton();
        processjButton = new javax.swing.JButton();
        declinejButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        organizationjLabel.setForeground(new java.awt.Color(255, 255, 102));
        organizationjLabel.setText("Organization");
        add(organizationjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 20));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 100, 20));

        workRequestJTable.setBackground(new java.awt.Color(204, 255, 255));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Reciever", "Status"
            }
        ));
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 138));

        assignjButton.setBackground(new java.awt.Color(255, 255, 204));
        assignjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        assignjButton.setText("Assign");
        assignjButton.setBorder(null);
        assignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignjButtonActionPerformed(evt);
            }
        });
        add(assignjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 98, 30));

        processjButton.setBackground(new java.awt.Color(255, 255, 204));
        processjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        processjButton.setText("Process");
        processjButton.setBorder(null);
        processjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processjButtonActionPerformed(evt);
            }
        });
        add(processjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 350, 110, 30));

        declinejButton.setBackground(new java.awt.Color(255, 255, 204));
        declinejButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        declinejButton.setText("Decline");
        declinejButton.setBorder(null);
        declinejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declinejButtonActionPerformed(evt);
            }
        });
        add(declinejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 94, 30));

        jButton1.setText("jButton1");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/photo-1516975080664-ed2fc6a32937.jpeg"))); // NOI18N
        jLabel1.setNextFocusableComponent(jButton1);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 660, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void assignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignjButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select at least one row");
            return;
        }

        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Confirmed");

        populateRequestTable();
    }//GEN-LAST:event_assignjButtonActionPerformed

    private void processjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processjButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select at least one row");
            return;
        }

        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow,0);
        request.setReceiver(userAccount);
        request.setStatus("Processed");
        populateRequestTable();
    }//GEN-LAST:event_processjButtonActionPerformed

    private void declinejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declinejButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select at least one row");
            return;
        }

        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Declined");

        populateRequestTable();
                              
    }//GEN-LAST:event_declinejButtonActionPerformed
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : salonorganization.getWorkQueue().getWorkRequestList()){
            if(request instanceof BeauticianWorkRequest){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignjButton;
    private javax.swing.JButton declinejButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel organizationjLabel;
    private javax.swing.JButton processjButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
